import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";

import { ourFileRouter } from "../app/api/uploadthing/core";

import { ClerkProvider } from "@clerk/nextjs";

import type { Metadata } from "next";

import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-providers";
import { cn } from "../lib/utils";
import { ModalProviders } from "@/components/providers/modal-providers";
import { SocketProvider } from "@/components/providers/socket-provider";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
      <ClerkProvider>
        <html lang="en" suppressContentEditableWarning>
          <body
            className={cn(
              font.className,
              "bg-white text-black dark:bg-[#202123] dark:text-white"
            )}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              storageKey="discord-clone-theme"
            >
              <SocketProvider>
                <ModalProviders />
                {children}
              </SocketProvider>
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}
